
import { notFound } from 'next/navigation'
import Profile from '@/Components/Profile'

export const metadata = {
  title: "CH Lead | Profile",
  description: "Generated by create next app",
};

async function getData(){
    const res = await fetch("http://localhost:3000/api/users", {cache: 'no-cache'});
    if(!res.ok) return notFound();
    return res.json();
}

const page = async() => {

    const userData = await getData()
    
  return (
    <div>
      <Profile userData ={userData}/>
    </div>
    )
}

export default page