
import AboutUs from '@/Components/AboutUs'

export const metadata = {
  title: "CH Lead | About Us",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <AboutUs/>
   
    </div>
  )
}

export default page